#include <stdio.h>
#include <string.h>
#include <math.h>

#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/semphr.h"
#include "esp_event.h"
#include "esp_log.h"
#include "esp_netif.h"
#include "esp_timer.h"
#include "esp_wifi.h"
#include "esp_heap_caps.h"
#include "nvs_flash.h"
#include "mqtt_client.h"
#include "cJSON.h"

#include "bsp/esp-bsp.h"
#include "iot_knob.h"
#include "lvgl.h"
#include "config.h"

static const char *TAG = "adsb-display";

struct AircraftDot { char flight[10]{}; char hex[8]{}; char squawk[5]{}; float distance_km=0; float bearing=0; float speed_kt=0; int altitude_ft=0; int track=0; };
struct Summary { int aircraft=0; int with_position=0; float msg_rate=0; float max_range_km=0; bool source_online=false; int age_seconds=0; AircraftDot nearest; };

static Summary g_summary; static AircraftDot g_planes[24]; static size_t g_plane_count=0;
static SemaphoreHandle_t g_data_mutex=nullptr; static volatile bool g_ui_dirty=true, g_wifi_connected=false, g_mqtt_connected=false, g_mqtt_started=false;
static esp_mqtt_client_handle_t g_mqtt=nullptr; static lv_display_t *g_display=nullptr; static knob_handle_t g_knob=nullptr;
static int g_page=0; static const int g_radar_ranges[]={25,50,100,200,400}; static int g_radar_range_idx=2;
static char g_alert[40]{}; static int64_t g_alert_until_ms=0;
static int64_t now_ms(){return esp_timer_get_time()/1000;}
static void log_heap(const char*w){ESP_LOGI(TAG,"heap %s: free=%u largest=%u",w,(unsigned)heap_caps_get_free_size(MALLOC_CAP_8BIT),(unsigned)heap_caps_get_largest_free_block(MALLOC_CAP_8BIT));}
static void json_copy(char*d,size_t n,const cJSON*i){if(!d||!n)return;d[0]=0;if(cJSON_IsString(i)&&i->valuestring)strlcpy(d,i->valuestring,n);}
static float json_float(const cJSON*o,const char*k,float d=0){const cJSON*v=cJSON_GetObjectItemCaseSensitive(o,k);return cJSON_IsNumber(v)?(float)v->valuedouble:d;}
static int json_int(const cJSON*o,const char*k,int d=0){const cJSON*v=cJSON_GetObjectItemCaseSensitive(o,k);return cJSON_IsNumber(v)?v->valueint:d;}
static void parse_plane(const cJSON*o,AircraftDot&a){memset(&a,0,sizeof(a));json_copy(a.flight,sizeof(a.flight),cJSON_GetObjectItemCaseSensitive(o,"flight"));json_copy(a.hex,sizeof(a.hex),cJSON_GetObjectItemCaseSensitive(o,"hex"));json_copy(a.squawk,sizeof(a.squawk),cJSON_GetObjectItemCaseSensitive(o,"squawk"));a.distance_km=json_float(o,"distance_km");a.bearing=json_float(o,"bearing");a.speed_kt=json_float(o,"speed_kt");a.altitude_ft=json_int(o,"altitude_ft");a.track=json_int(o,"track");}
static bool topic_ends_with(esp_mqtt_event_handle_t e,const char*s){size_t n=strlen(s);return e&&e->topic&&e->topic_len>=(int)n&&!memcmp(e->topic+e->topic_len-n,s,n);}
static void handle_summary(const char*d,int l){cJSON*r=cJSON_ParseWithLength(d,l);if(!r)return;if(xSemaphoreTake(g_data_mutex,pdMS_TO_TICKS(100))){g_summary.aircraft=json_int(r,"aircraft");g_summary.with_position=json_int(r,"with_position");g_summary.msg_rate=json_float(r,"msg_rate");g_summary.max_range_km=json_float(r,"max_range_km");g_summary.age_seconds=json_int(r,"age_seconds");g_summary.source_online=cJSON_IsTrue(cJSON_GetObjectItemCaseSensitive(r,"source_online"));const cJSON*n=cJSON_GetObjectItemCaseSensitive(r,"nearest");if(cJSON_IsObject(n))parse_plane(n,g_summary.nearest);xSemaphoreGive(g_data_mutex);g_ui_dirty=true;}cJSON_Delete(r);}
static void handle_aircraft(const char*d,int l){cJSON*r=cJSON_ParseWithLength(d,l);if(!cJSON_IsArray(r)){cJSON_Delete(r);return;}if(xSemaphoreTake(g_data_mutex,pdMS_TO_TICKS(100))){g_plane_count=0;cJSON*i=nullptr;cJSON_ArrayForEach(i,r){if(g_plane_count>=24)break;if(cJSON_IsObject(i))parse_plane(i,g_planes[g_plane_count++]);}xSemaphoreGive(g_data_mutex);ESP_LOGI(TAG,"aircraft update: %u planes",(unsigned)g_plane_count);g_ui_dirty=true;}cJSON_Delete(r);}
static void handle_alert(const char*d,int l){cJSON*r=cJSON_ParseWithLength(d,l);if(!r)return;const cJSON*e=cJSON_GetObjectItemCaseSensitive(r,"event"),*f=cJSON_GetObjectItemCaseSensitive(r,"flight"),*q=cJSON_GetObjectItemCaseSensitive(r,"squawk");const char*ev=cJSON_IsString(e)?e->valuestring:"ALERT";const char*id=cJSON_IsString(f)&&f->valuestring&&f->valuestring[0]?f->valuestring:(cJSON_IsString(q)?q->valuestring:"");snprintf(g_alert,sizeof(g_alert),"%s %s",ev,id?id:"");g_alert_until_ms=now_ms()+12000;g_ui_dirty=true;cJSON_Delete(r);}
static void mqtt_event(void*,esp_event_base_t,int32_t id,void*data){auto e=(esp_mqtt_event_handle_t)data;switch((esp_mqtt_event_id_t)id){case MQTT_EVENT_CONNECTED:{ESP_LOGI(TAG,"MQTT connected");g_mqtt_connected=true;char t[96];snprintf(t,sizeof(t),"%s/summary",MQTT_BASE_TOPIC);esp_mqtt_client_subscribe(g_mqtt,t,0);snprintf(t,sizeof(t),"%s/aircraft",MQTT_BASE_TOPIC);esp_mqtt_client_subscribe(g_mqtt,t,0);snprintf(t,sizeof(t),"%s/alert",MQTT_BASE_TOPIC);esp_mqtt_client_subscribe(g_mqtt,t,0);g_ui_dirty=true;break;}case MQTT_EVENT_DISCONNECTED:g_mqtt_connected=false;g_ui_dirty=true;ESP_LOGW(TAG,"MQTT disconnected");break;case MQTT_EVENT_DATA:if(e&&e->current_data_offset==0&&e->data_len==e->total_data_len){if(topic_ends_with(e,"/summary"))handle_summary(e->data,e->data_len);else if(topic_ends_with(e,"/aircraft"))handle_aircraft(e->data,e->data_len);else if(topic_ends_with(e,"/alert"))handle_alert(e->data,e->data_len);}break;default:break;}}
static bool prepare_mqtt(){if(g_mqtt)return true;log_heap("before mqtt init");static char uri[128];snprintf(uri,sizeof(uri),"mqtt://%s:%d",MQTT_HOST,MQTT_PORT);esp_mqtt_client_config_t c={};c.broker.address.uri=uri;c.credentials.client_id=DEVICE_NAME;if(strlen(MQTT_USERNAME)){c.credentials.username=MQTT_USERNAME;c.credentials.authentication.password=MQTT_PASSWORD;}c.buffer.size=6144;g_mqtt=esp_mqtt_client_init(&c);if(!g_mqtt)return false;if(esp_mqtt_client_register_event(g_mqtt,MQTT_EVENT_ANY,mqtt_event,nullptr)!=ESP_OK)return false;log_heap("after mqtt init");return true;}
static void start_mqtt(){if(!g_mqtt||g_mqtt_started)return;if(esp_mqtt_client_start(g_mqtt)==ESP_OK){g_mqtt_started=true;ESP_LOGI(TAG,"MQTT client started");}}
static void wifi_event(void*,esp_event_base_t b,int32_t id,void*){if(b==WIFI_EVENT&&id==WIFI_EVENT_STA_START)esp_wifi_connect();else if(b==WIFI_EVENT&&id==WIFI_EVENT_STA_DISCONNECTED){g_wifi_connected=false;g_mqtt_connected=false;g_ui_dirty=true;esp_wifi_connect();}else if(b==IP_EVENT&&id==IP_EVENT_STA_GOT_IP){g_wifi_connected=true;g_ui_dirty=true;ESP_LOGI(TAG,"Wi-Fi connected");start_mqtt();}}
static void wifi_init(){ESP_ERROR_CHECK(esp_netif_init());ESP_ERROR_CHECK(esp_event_loop_create_default());ESP_ERROR_CHECK(esp_netif_create_default_wifi_sta()?ESP_OK:ESP_FAIL);wifi_init_config_t c=WIFI_INIT_CONFIG_DEFAULT();ESP_ERROR_CHECK(esp_wifi_init(&c));ESP_ERROR_CHECK(esp_event_handler_register(WIFI_EVENT,ESP_EVENT_ANY_ID,wifi_event,nullptr));ESP_ERROR_CHECK(esp_event_handler_register(IP_EVENT,IP_EVENT_STA_GOT_IP,wifi_event,nullptr));wifi_config_t w={};strlcpy((char*)w.sta.ssid,WIFI_SSID,sizeof(w.sta.ssid));strlcpy((char*)w.sta.password,WIFI_PASSWORD,sizeof(w.sta.password));w.sta.threshold.authmode=WIFI_AUTH_WPA2_PSK;ESP_ERROR_CHECK(esp_wifi_set_mode(WIFI_MODE_STA));ESP_ERROR_CHECK(esp_wifi_set_config(WIFI_IF_STA,&w));ESP_ERROR_CHECK(esp_wifi_start());}
static lv_obj_t*label(lv_obj_t*p,const char*t,int y){lv_obj_t*o=lv_label_create(p);lv_label_set_text(o,t);lv_obj_set_style_text_color(o,lv_color_white(),0);lv_obj_align(o,LV_ALIGN_TOP_MID,0,y);return o;}
static void title(lv_obj_t*s,const char*t){lv_obj_t*o=label(s,t,12);lv_obj_set_style_text_color(o,lv_color_hex(0x00d7ff),0);}
static void draw_overview(lv_obj_t*s,const Summary&x){title(s,"ADS-B");lv_obj_t*a=label(s,"",48);lv_label_set_text_fmt(a,"%d AIRCRAFT",x.aircraft);lv_obj_set_style_text_color(a,x.source_online?lv_color_hex(0x50e050):lv_color_hex(0xff4040),0);lv_obj_t*i=label(s,"",82);lv_label_set_text_fmt(i,"POS %d\nMSG/S %.0f\nMAX %.0f km",x.with_position,x.msg_rate,x.max_range_km);lv_obj_set_style_text_align(i,LV_TEXT_ALIGN_CENTER,0);const auto&n=x.nearest;const char*id=n.flight[0]?n.flight:(n.hex[0]?n.hex:"---");lv_obj_t*q=label(s,"",150);lv_label_set_text_fmt(q,"NEAREST %s\n%.1f km %d ft",id,n.distance_km,n.altitude_ft);lv_obj_set_style_text_align(q,LV_TEXT_ALIGN_CENTER,0);}
static void draw_nearest(lv_obj_t*s,const Summary&x){title(s,"NEAREST");const auto&a=x.nearest;const char*id=a.flight[0]?a.flight:(a.hex[0]?a.hex:"---");lv_obj_t*o=label(s,"",52);lv_label_set_text_fmt(o,"%s\n%.1f km\n%d ft\n%.0f kt\nTRK %d\nSQ %s",id,a.distance_km,a.altitude_ft,a.speed_kt,a.track,a.squawk[0]?a.squawk:"----");lv_obj_set_style_text_align(o,LV_TEXT_ALIGN_CENTER,0);}
static void draw_status(lv_obj_t*s,const Summary&x){title(s,"RECEIVER");lv_obj_t*o=label(s,"",58);lv_label_set_text_fmt(o,"%s\n\nWi-Fi %s\nMQTT %s\nData age %d s",x.source_online?"SOURCE ONLINE":"SOURCE OFFLINE",g_wifi_connected?"OK":"DOWN",g_mqtt_connected?"OK":"DOWN",x.age_seconds);lv_obj_set_style_text_align(o,LV_TEXT_ALIGN_CENTER,0);}
static void dot(lv_obj_t*r,int x,int y,bool em){lv_obj_t*d=lv_obj_create(r);lv_obj_remove_style_all(d);lv_obj_set_size(d,em?7:5,em?7:5);lv_obj_set_style_radius(d,LV_RADIUS_CIRCLE,0);lv_obj_set_style_bg_opa(d,LV_OPA_COVER,0);lv_obj_set_style_bg_color(d,em?lv_color_hex(0xff3030):lv_color_white(),0);lv_obj_align(d,LV_ALIGN_CENTER,x,y);}
static void draw_radar(lv_obj_t*s,const AircraftDot*p,size_t count){float range=(float)g_radar_ranges[g_radar_range_idx];char h[32];snprintf(h,sizeof(h),"RADAR %d km",(int)range);title(s,h);lv_obj_t*r=lv_obj_create(s);lv_obj_remove_style_all(r);lv_obj_set_size(r,164,164);lv_obj_align(r,LV_ALIGN_CENTER,0,8);lv_obj_set_style_radius(r,LV_RADIUS_CIRCLE,0);lv_obj_set_style_bg_opa(r,LV_OPA_COVER,0);lv_obj_set_style_bg_color(r,lv_color_black(),0);lv_obj_set_style_border_width(r,1,0);lv_obj_set_style_border_color(r,lv_color_hex(0x606060),0);lv_obj_clear_flag(r,LV_OBJ_FLAG_SCROLLABLE);lv_obj_t*n=lv_label_create(r);lv_label_set_text(n,"N");lv_obj_set_style_text_color(n,lv_color_hex(0x00d7ff),0);lv_obj_align(n,LV_ALIGN_TOP_MID,0,2);dot(r,0,0,false);size_t shown=0;for(size_t i=0;i<count;i++){if(p[i].distance_km<=0||p[i].distance_km>range)continue;float a=(p[i].bearing-90.0f)*3.14159265f/180.0f,rr=(p[i].distance_km/range)*72.0f;int x=(int)(cosf(a)*rr),y=(int)(sinf(a)*rr);bool em=!strcmp(p[i].squawk,"7500")||!strcmp(p[i].squawk,"7600")||!strcmp(p[i].squawk,"7700");dot(r,x,y,em);shown++;}lv_obj_t*c=label(s,"",211);lv_label_set_text_fmt(c,"%u/%u",(unsigned)shown,(unsigned)count);}
static void render_ui(){Summary s;AircraftDot p[24];size_t n;if(!xSemaphoreTake(g_data_mutex,pdMS_TO_TICKS(100)))return;s=g_summary;n=g_plane_count;memcpy(p,g_planes,sizeof(p));xSemaphoreGive(g_data_mutex);if(!bsp_display_lock(1000))return;lv_obj_t*screen=lv_screen_active();lv_obj_clean(screen);lv_obj_set_style_bg_color(screen,lv_color_black(),0);lv_obj_set_style_bg_opa(screen,LV_OPA_COVER,0);if(g_page==0)draw_overview(screen,s);else if(g_page==1)draw_radar(screen,p,n);else if(g_page==2)draw_nearest(screen,s);else draw_status(screen,s);bsp_display_unlock();}
static void knob_left(void*,void*){if(g_page==1){if(--g_radar_range_idx<0)g_radar_range_idx=4;}else{if(--g_page<0)g_page=3;}g_ui_dirty=true;}
static void knob_right(void*,void*){if(g_page==1){if(++g_radar_range_idx>4)g_radar_range_idx=0;}else{if(++g_page>3)g_page=0;}g_ui_dirty=true;}
static void knob_press(void*,void*){g_page=(g_page+1)%4;g_ui_dirty=true;}
static void init_knob(){knob_config_t c={};c.default_direction=0;c.gpio_encoder_a=BSP_ENCODER_A;c.gpio_encoder_b=BSP_ENCODER_B;g_knob=iot_knob_create(&c);if(g_knob){iot_knob_register_cb(g_knob,KNOB_LEFT,knob_left,nullptr);iot_knob_register_cb(g_knob,KNOB_RIGHT,knob_right,nullptr);ESP_LOGI(TAG,"Encoder callbacks active");}button_handle_t b=bsp_iot_button_create(BSP_BUTTON_PRESS,nullptr);if(b){iot_button_register_cb(b,BUTTON_SINGLE_CLICK,nullptr,knob_press,nullptr);ESP_LOGI(TAG,"Button callback active");}}
static void ui_task(void*){while(true){if(g_alert[0]&&now_ms()>=g_alert_until_ms){g_alert[0]=0;g_ui_dirty=true;}if(g_ui_dirty){g_ui_dirty=false;render_ui();}vTaskDelay(pdMS_TO_TICKS(100));}}
extern "C" void app_main(void){ESP_LOGI(TAG,"ADS-B LCDkit ESP-IDF/BSP build starting");esp_err_t e=nvs_flash_init();if(e==ESP_ERR_NVS_NO_FREE_PAGES||e==ESP_ERR_NVS_NEW_VERSION_FOUND){ESP_ERROR_CHECK(nvs_flash_erase());e=nvs_flash_init();}ESP_ERROR_CHECK(e);g_data_mutex=xSemaphoreCreateMutex();ESP_ERROR_CHECK(g_data_mutex?ESP_OK:ESP_ERR_NO_MEM);if(!prepare_mqtt())ESP_LOGE(TAG,"MQTT preparation failed");ESP_LOGI(TAG,"Starting official ESP32-C3-LCDkit BSP display");g_display=bsp_display_start();ESP_ERROR_CHECK(g_display?ESP_OK:ESP_FAIL);ESP_ERROR_CHECK(bsp_display_backlight_on());init_knob();xTaskCreate(ui_task,"adsb-ui",4096,nullptr,4,nullptr);ESP_LOGI(TAG,"Starting Wi-Fi");wifi_init();}
