[env:esp32-c3-lcdkit]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
board_build.flash_mode = dio
build_flags =
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D USER_SETUP_LOADED=1
  -D GC9A01_DRIVER=1
  -D TFT_WIDTH=240
  -D TFT_HEIGHT=240
  -D TFT_MOSI=0
  -D TFT_SCLK=1
  -D TFT_CS=7
  -D TFT_DC=2
  -D TFT_RST=-1
  -D TFT_BL=5
  -D TFT_BACKLIGHT_ON=HIGH
  -D LOAD_GLCD=1
  -D LOAD_FONT2=1
  -D LOAD_FONT4=1
  -D SPI_FREQUENCY=40000000
lib_deps =
  bodmer/TFT_eSPI @ ^2.5.43
  knolleary/PubSubClient @ ^2.8
  bblanchon/ArduinoJson @ ^7.2.1
  adafruit/Adafruit NeoPixel @ ^1.12.3
